[tool.poetry]
name = "nonebot-adapter-dodo"
version = "0.1.0"
description = "Dodo adapter for nonebot2"
authors = ["CMHopeSunshine <277073121@qq.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/nonebot/adapter-dodo"
repository = "https://github.com/nonebot/adapter-dodo"
documentation = "https://github.com/nonebot/adapter-dodo"
keywords = ["nonebot", "dodo", "bot"]

packages = [{ include = "nonebot" }]

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = "^2.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.4"
nonemoji = "^0.1.2"
pre-commit = "^3.1.0"

[tool.ruff]
select = ["E", "W", "F", "I", "UP", "C", "T", "PYI", "PT", "Q"]
ignore = ["E402", "F403", "F405", "C901", "PYI021", "PYI048"]
line-length = 88
target-version = "py38"
ignore-init-module-imports = true


[tool.ruff.isort]
force-sort-within-sections = true
extra-standard-library = ["typing_extensions"]
force-wrap-aliases = true
combine-as-imports = true
order-by-type = true
relative-imports-order = "closest-to-furthest"
section-order = [
    "future",
    "standard-library",
    "first-party",
    "third-party",
    "local-folder",
]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
